### ISSUE TITLE
Fix selrafsi

### ISSUE THREAD

**Issue by skytomo221** [skytomo221/jvozba-npm#4]
長いrafsiに対してselrafsi関数が正常にselrafsiを返していません。

![image](https://user-images.githubusercontent.com/18415838/154806734-0426d1c8-cb98-4490-bd7b-d06b97467371.png)

例えば、mabruのselrafsiはmabruですが、エラーが発生します。

**Comment by niftg** [comment]
[docs/difference.md](https://github.com/skytomo221/jvozba-npm/blob/master/docs/difference.md)を見たところ

- `tools/search_selrafsi_from_rafsi2`がRemovedで、
- `tools/search_selrafsi_from_rafsi`が`selrafsi/selrafsi`として取り込まれてる

様ですが、`…_rafsi2`の方にも割と大事な雑務が含まれてるみたいなので、いい感じに取り込んでみると良いかもしれません

**Comment by niftg** [comment]
と思ったらそれをまた別の仕方で解決したのが #5 ("Fix selrafsi")で、こちらでも確認して承認するとマージされる感じなんですね。.ai vi'o catlu cpedu
